name: GHUserComponent
on: [push]

jobs:
  build_ghuser_components:
    runs-on: windows-latest
    name: Build components
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5

      - name: Install Python and pythonnet
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
      - name: Install pythonnet
        run: |
          pip install pythonnet
      - uses: ./.github/actions/ghpython-components
        with:
          source: GH\PyGH\components
          target: GH\PyGH\build
      
      - uses: actions/upload-artifact@v2
        with:
          name: ghuser-components
          path: GH\PyGH\build