name: RhinoPlugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8'  # replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore ./CsRhino/ScriptSync.csproj  # replace with your .csproj path

    - name: Build
      run: dotnet build ./CsRhino/ScriptSync.csproj --configuration Release --no-restore

    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: CsRhino.rhp
        path: ./CsRhino/bin/Release/netcoreapp3.1/CsRhino.rhp  # replace with the path to your .rhp file