name: RhinoPlugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #install net48
    - name: Install .NET Framework 4.8
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: dotnet restore ./CsRhino/ScriptSync.csproj

    - name: Build
      run: dotnet build ./CsRhino/ScriptSync.csproj --configuration Release --no-restore

    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScriptSync.rhp
        path: ./CsRhino/bin/Release/net48/