name: VSCodeExtension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Python setup
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Install pip and invoke
      run: |
          python -m pip install --upgrade pip
          pip install invoke

    - name: Sync version
      run: invoke syncv

    - name: Install vsce
      run: npm install -g vsce

    - name: Build VSIX package
      run: |
        cd VSCode/scriptsync
        npm install
        vsce package

    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: script-sync
        path: VSCode/scriptsync/*.vsix